### ISSUE TITLE
No data for multipolygons layer in Greater London

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/geofabric#16]
Not sure what's causing this.

Reprex:

```
library(geofabric)
View(geofabric_zones)
lnd_osm = geofabric::get_geofabric(name = "greater london", layer = "multipolygons")
nrow(lnd_osm)
```

**Comment by agila5** [comment]
As Edzer showed in https://github.com/r-spatial/sf/issues/1213#issuecomment-563975428 , this is the same issue as #12 since the MULTIPOLYGONS layer was not read for the "Too many features have accumulated in points layer..." error
