### ISSUE TITLE
Set-up CI

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/geofabric#19]

**Comment by Robinlovelace** [comment]
Heads-up @layik this is WiP: https://travis-ci.org/itsleeds/geofabric

**Comment by agila5** [comment]
I think I fixed the previous comments but the problem now is the following: 

Error: No deploy key found, please setup with `travis::use_travis_deploy()`

but, even if I run `travis::use_travis_deploy()` I get an error since I don't have role admin in the repo ITSLeeds/geofabric, just write.

**Comment by Robinlovelace** [comment]
Many thanks @agila5, will take a look now, great work!

**Comment by Robinlovelace** [comment]
Seems to be fixed :tada:
