### ISSUE TITLE
Create data frame representing complete map of downloads available from geofabric

### ISSUE THREAD

**Issue by Robinlovelace** [ITSLeeds/geofabric#2]
May be up your street @layik, see here for starting point:

https://github.com/salimk/Rcrawler

Maybe clever JS ways to identify all .pbf endpoints on all pages of this relatively small website: http://download.geofabrik.de/

**Comment by layik** [comment]
Thanks Robin. Not quite clear, but yes I liked geofabrik so I am interested.
